### ISSUE TITLE
Calling Sam#to_s when Fasta file not specified raises an Exception

### ISSUE THREAD

**Issue by timpalpant** [helios/bioruby-samtools#2]
If the fasta file is not set when calling Sam.new(), then calling to_s will raise an Exception since it attempts to include the fasta file name (nil). It should probably check for nil and then say 'not set' or something.

```ruby
irb(main):001:0> require 'bio/db/sam'
=> true
irb(main):002:0> sam = Bio::DB::Sam.new(:bam => 'test.bam')
TypeError: can't convert nil into String
        from /opt/local/lib/ruby1.9/gems/1.9.1/gems/bio-samtools-0.2.0/lib/bio/db/sam.rb:77:in `+'
        from /opt/local/lib/ruby1.9/gems/1.9.1/gems/bio-samtools-0.2.0/lib/bio/db/sam.rb:77:in `to_s'
        from /opt/local/bin/irb1.9:12:in `<main>'
```

**Comment by homonecloco** [comment]
The current implementation forces in the constructor the precedes of both the bam and the sam file (it raises an exception in the constructor if it is missing). Is this an acceptable solution. I know this has been open for a while, but I can't track the offending code.
