### ISSUE TITLE
iterating alignments

### ISSUE THREAD

**Issue by wwood** [helios/bioruby-samtools#25]
Hi,

Just wondering if there is any way to iterate over all alignments in a sam/bam file, without specifying a chromosome & start and stop positions?

i'm thinking an each_alignment method, like iterating over the lines from a  ```samtools view```, except giving Alignment objects, rather than a string.

Thanks,
ben

**Comment by homonecloco** [comment]
I think this is sorted with release 2.0, right?

**Comment by danmaclean** [comment]
Yeah, this is the `Bio::DB::Sam.view`
