### ISSUE TITLE
rmdups fails using samtools v1.0+

### ISSUE THREAD

**Issue by ethering** [helios/bioruby-samtools#39]
SAMtools rmdup is broken and hence unit test in test_sam.rb test_rmdup() using SAMtools 1.0 and above fail.
The failure of rmdup in SAMtools v1.0+ is well documented.
https://github.com/samtools/samtools/issues/159
https://github.com/samtools/samtools/issues/252
https://github.com/samtools/samtools/issues/138

I'd suggest at least removing the test until it's fixed.

The unit tests also throws an error (rather than a failure) on:
 => 14:       File.delete("test/samples/small/dupes_rmdup.bam")

This line should also be removed for now (dupes_rmdup.bam should be the outfile from the rmdup test).

**Comment by danmaclean** [comment]
I would leave the test. The point of the test is to show us that something is broken - so its doing a good job.

**Comment by homonecloco** [comment]
So, I´m half way to add support to versions 1+, what I'm thinking to do for this method is to have both versions compiled, and fall back to version 0.1.19 when rmdup is called, and once it is fixed in samtools we can get it running. What do you think about that solution, so it doesn't break the legacy code and we can have the new functionality exposed?

**Comment by danmaclean** [comment]
Im nervous about this approach because we end up with a hybrid application - the user isn't certain which SAMtools they are on.. soo I say we report to the user - this fails with this SAMtools, change to this SAMtools to use it...

**Comment by jmarshall** [comment]
Note that this has since been fixed (see PR samtools/samtools#461); an `rmdup` command that works as well as it ever did will reappear in the upcoming samtools 1.3 release.

**Comment by homonecloco** [comment]
Thanks for the update. We'll update the library once samtools 1.3 is released :)

**Comment by homonecloco** [comment]
The gem was updated to samtools 1.3.1, and the rmdup tests are working.
