### ISSUE TITLE
Is this project using FFI? (Question about current status)

### ISSUE THREAD

**Issue by kojix2** [helios/bioruby-samtools#73]
Hello, @homonecloco and bioruby-samtools developers.

Thank you for your great work.

I am kojix2 and I'm now trying to develop ruby-htslib.
* https://github.com/kojix2/ruby-htslib

Before creating ruby-htslib, I looked for similar projects. Because when reinventing the wheel, it's important to observe previous good projects. I found your bioruby-samtools. I read the README of bioruby-samtools. It said it uses FFI.

> Binder of samtools for ruby, on the top of FFI.

But, from looking at the project a bit, it doesn't look like there is any part of it that uses FFI.
Instead, it loos like it is using open3.
I think it probably meant that it used FFI in the past, and now using Open3.
Is that right?

Thank you.

**Comment by homonecloco** [comment]
Hi, the first version we did used to use FFI on samtools 0.19, or something like that, before HTSLib. But when HTSLib  was introduced, all the calls broke. So we decided to use Open3 while the API was stable. Then we never got back to do this again. I'm glad you are doing this, and I'm happy to give my input and help a bit on this. I'd been intending to do this bindings, but I haven't got the excuse to focus on this project.

**Comment by kojix2** [comment]
Thank you for your reply. I understand very well.
I'm a graduate student in Japan. I would like to study and try to make ruby-htslib somehow. The new Ruby was released on Christmas. However, this year is very difficult because of the virus epidemic everywhere on the earth. Please take care of your health. Hope you are well!
